packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^22.10.10
  eslint: ^9.19.0
  lucide-react: ^0.511.0
  prettier: ^3.5.3
  tailwindcss: ^4
  typescript: ^5.7.3
  zod: ^3.24.2

catalogs:
  react:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
